# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Kasim Te
tagline:          'A website.'
description:      "Hi, I'm Kasim."
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kasim Te'
  url:            https://twitter.com/kasimte

paginate:         5

# Custom vars

github:
  repo:           https://github.com/kasimte

